#import <Foundation/Foundation.h>
#import "SWGInventoryItem.h"
#import "SWGApi.h"

/**
* Simple Inventory API
* This is a simple API
*
* OpenAPI spec version: 1.0.0
* Contact: you@your-company.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/


@interface SWGPublicOperationsApi: NSObject <SWGApi>

extern NSString* kSWGPublicOperationsApiErrorDomain;
extern NSInteger kSWGPublicOperationsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// searches inventory
/// By passing in the appropriate options, you can search for available inventory in the system 
///
/// @param searchString pass an optional search string for looking up inventory (optional)
/// @param skip number of records to skip for pagination (optional)
/// @param limit maximum number of records to return (optional)
/// 
///  code:200 message:"search results matching criteria",
///  code:400 message:"bad input parameter"
///
/// @return NSArray<SWGInventoryItem>*
-(NSNumber*) searchInventoryWithSearchString: (NSString*) searchString
    skip: (NSNumber*) skip
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<SWGInventoryItem>* output, NSError* error)) handler;



@end
