//
// AdminOperationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class AdminOperationsAPI: APIBase {
    /**
     adds an inventory item
     
     - parameter inventoryItem: (body) Inventory item to add (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addInventory(inventoryItem inventoryItem: InventoryItem? = nil, completion: ((error: ErrorType?) -> Void)) {
        addInventoryWithRequestBuilder(inventoryItem: inventoryItem).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     adds an inventory item
     - POST /inventory
     - Adds an item to the system
     
     - parameter inventoryItem: (body) Inventory item to add (optional)

     - returns: RequestBuilder<Void> 
     */
    public class func addInventoryWithRequestBuilder(inventoryItem inventoryItem: InventoryItem? = nil) -> RequestBuilder<Void> {
        let path = "/inventory"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = inventoryItem?.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
