//
// PublicOperationsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PublicOperationsAPI: APIBase {
    /**
     searches inventory
     
     - parameter searchString: (query) pass an optional search string for looking up inventory (optional)
     - parameter skip: (query) number of records to skip for pagination (optional)
     - parameter limit: (query) maximum number of records to return (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func searchInventory(searchString searchString: String? = nil, skip: Int32? = nil, limit: Int32? = nil, completion: ((data: [InventoryItem]?, error: ErrorType?) -> Void)) {
        searchInventoryWithRequestBuilder(searchString: searchString, skip: skip, limit: limit).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     searches inventory
     - GET /inventory
     - By passing in the appropriate options, you can search for available inventory in the system 
     - examples: [{contentType=application/json, example=[ {
  "releaseDate" : "2015-08-29T09:12:33.001Z",
  "name" : "Widget Adapter",
  "id" : "d290f1ee-asdqwe-4b01-90e6-d701748f0851",
  "manufacturer" : {
    "phone" : "408-867-5309",
    "name" : "ACME Corporation updated",
    "homePage" : "https://www.acme-corp.com"
  }
} ]}]
     
     - parameter searchString: (query) pass an optional search string for looking up inventory (optional)
     - parameter skip: (query) number of records to skip for pagination (optional)
     - parameter limit: (query) maximum number of records to return (optional)

     - returns: RequestBuilder<[InventoryItem]> 
     */
    public class func searchInventoryWithRequestBuilder(searchString searchString: String? = nil, skip: Int32? = nil, limit: Int32? = nil) -> RequestBuilder<[InventoryItem]> {
        let path = "/inventory"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "searchString": searchString,
            "skip": skip?.encodeToJSON(),
            "limit": limit?.encodeToJSON()
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[InventoryItem]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
