/**
 * This is a demo API
 * API to control the Tesla Model S
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse200 {
  
  @SerializedName("color")
  private String color = null;
  @SerializedName("vin")
  private String vin = null;
  @SerializedName("display_name")
  private String displayName = null;
  @SerializedName("vehicle_id")
  private String vehicleId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getColor() {
    return color;
  }
  public void setColor(String color) {
    this.color = color;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVin() {
    return vin;
  }
  public void setVin(String vin) {
    this.vin = vin;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getVehicleId() {
    return vehicleId;
  }
  public void setVehicleId(String vehicleId) {
    this.vehicleId = vehicleId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return (this.color == null ? inlineResponse200.color == null : this.color.equals(inlineResponse200.color)) &&
        (this.vin == null ? inlineResponse200.vin == null : this.vin.equals(inlineResponse200.vin)) &&
        (this.displayName == null ? inlineResponse200.displayName == null : this.displayName.equals(inlineResponse200.displayName)) &&
        (this.vehicleId == null ? inlineResponse200.vehicleId == null : this.vehicleId.equals(inlineResponse200.vehicleId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.color == null ? 0: this.color.hashCode());
    result = 31 * result + (this.vin == null ? 0: this.vin.hashCode());
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.vehicleId == null ? 0: this.vehicleId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("  color: ").append(color).append("\n");
    sb.append("  vin: ").append(vin).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  vehicleId: ").append(vehicleId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
