//
// InventoryItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class InventoryItem: JSONEncodable {
    public var id: NSUUID?
    public var name: String?
    public var releaseDate: String?
    public var manufacturer: ManufacturerUp?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["releaseDate"] = self.releaseDate
        nillableDictionary["manufacturer"] = self.manufacturer?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
